### ISSUE TITLE
Average Depth Report - minimum depth is positive number

### ISSUE THREAD

**Issue by mmosesOCMP** [orcoastalmgmt/orSeaSketch#9]
Minimum depth is positive number, sometimes greater than the veg line or extreme high water line, and unclear whether it is excluding data from offshore rocks and islands, which would be under USFWS jurisdiction and technically not the state.

**Comment by tchaddad** [comment]
Steps to reproduce:

- load a report for any sketch
- look at physical section of the report
- take a look at minimum depth

![problem_with_depth_calculation](https://user-images.githubusercontent.com/1042618/78921920-870a7700-7a4a-11ea-853c-535132c70c6b.PNG)

**Comment by tchaddad** [comment]
This one is for the SeaSketch team

**Comment by mmosesOCMP** [comment]
![image](https://user-images.githubusercontent.com/62967932/81964045-ec620280-95ca-11ea-8a85-c4f39523f65a.png)

It seems as though minimum depth is calculating from the unclipped polygons. If this is the case, it would be preferable to calculate only from the clipped polygon.

We should also add the following explanatory text above the report: "Positive values for minimum depth represents elevation above mean lower low water."

**Comment by tchaddad** [comment]
We think this is happening because we are using a 100m grid for the bathy, and so for areas with cliffs, the calculations may be producing high positive numbers simply because we are catching the cliff in the cells on the landward side of the clip.

Only the SeaSketch team can confirm if the calculation is being performed on the pre- or post- clipped polygon. Obviously we prefer using the clipped polygon.

TEXT TO ADD TO REPORT: "Positive values for minimum depth represents elevation above mean lower low water. Unusually high values indicate cliff edges that fall within 100m of Mean High Water."

**Comment by danyocum** [comment]
We always use the clipped sketches in the report calculations, so its post-clipped. The data file I'm using for the bathymetry is:

PHY_Bathymetry100m_ATSML_2011_clipped

**Comment by danyocum** [comment]
I've added the text to the report.
